export const states = [
  'Amazonas',
  'Anzoátegui',
  'Apure',
  'Aragua',
  'Barinas',
  'Bolívar',
  'Carabobo',
  'Cojedes',
  'Delta Amacuro',
  'Falcón',
  'Lara',
  'Miranda',
  'Monagas',
  'Nueva Esparta',
  'Portuguesa',
  'Sucre',
  'Táchira',
  'Trujillo',
  'Yaracuy',
  'Zulia',
  'Distrito Capital',
  'Dependencias Federales',
]

export const specialtys = [
  'Medicina Interna',
  'Gineco-Obstetra',
  'Odontologia',
  'Dermatologia',
  'Psiquiatria',
  'Cardiologia',
  'Pediatria',
  'Oftalmologia',
  'Traumatologia',
  'Neumonologia',
  'Gastroenterologia',
  'Urologia',
]
